### ISSUE TITLE
[Bug]: Stuck in preview screen

### ISSUE THREAD

**Issue by ghillieee** [CMGStudios/minigames-issue-tracker#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Stuck in preview screen of deadline https://medal.tv/games/gta-v/clips/p2VxbRVctciOW/d13376XRlipG?invite=cr-MSxjMkosMjcyODE4MzYs

### Expected behaviour

Join deadline and dead some lines

### Steps to reproduce

Join deadline at like 1s
Enjoy the preview screen 

### Any Texture Packs? (If so list)

I CANT REMEBER

### CMG User ID

221197 or 410

**Comment by crazychris2404** [comment]
Could not reproduce this issue during testing if you can get this to reoccur please comment on this issue
