### ISSUE TITLE
[Bug]: Party Order

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/minigames-issue-tracker#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in a party the party leader should appear before everyone else, meaning the party leader should always appear first in the party screen
![image](https://user-images.githubusercontent.com/88695973/174688841-b19046a7-08ed-4e22-be1b-caa39059a486.png)

### Expected behaviour

The leader should always be the first one in the Party screen

### Steps to reproduce

1. Invite Friend
2. Check party Order
3. Leader is not first in order

### CMG User ID

63

**Comment by crazychris2404** [comment]
This is confirmed and currently being worked on
