### ISSUE TITLE
[Bug]: Party ready up

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/minigames-issue-tracker#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The leader also needs to ready up

### Expected behaviour

The leader should not need to ready up

### Steps to reproduce

Join a party
Everyone readies up except leader
try and join a game

### CMG User ID

63

**Comment by crazychris2404** [comment]
I have spoken to developers and this is a intended feature.
You can suggest changes to it [here](https://canary.discord.com/channels/939537628326395994/982758512985772142)
