### ISSUE TITLE
[Bug]: everyone can see your deathmatch kills in chat when you type the command [cmg deathmatch]

### ISSUE THREAD

**Issue by Yiqqa** [CMGStudios/minigames-issue-tracker#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

everyone can see your deathmatch kills in chat when you type the command

### Expected behaviour

when you type /deathmatchkills in chat everyone can see it

### Steps to reproduce

type /deathmatchkills in chat [cmg deathmatch]

### Any Texture Packs? (If so list)

no

### CMG User ID

1131

**Comment by crazychris2404** [comment]
This has now been resolved
