### ISSUE TITLE
[Bug]: No car in races

### ISSUE THREAD

**Issue by pachxl** [CMGStudios/minigames-issue-tracker#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

seem to skip the cinematic phase and just see your ped standing there, then you end up in the cinematic phase but at that point everyone is already picking their cars, when the race starts you don't have a car

### Expected behaviour

Should be able to pick a car and enter the race

### Steps to reproduce

not sure exactly what caused it but this is the error i got
@cmg/client_prod/minigames/cl_dynamicraces.lua:1: table index is nil

### Any Texture Packs? (If so list)

no

### CMG User ID

365

**Comment by crazychris2404** [comment]
Do you have a video of this occuring?

**Comment by crazychris2404** [comment]
Confirmed 
The cause is joining the race last second
