### ISSUE TITLE
[Bug]: put me in the air 

### ISSUE THREAD

**Issue by stony5** [CMGStudios/minigames-issue-tracker#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 nuke town map its this map puts you in the air it happens in tdm and ffa etc clip- https://youtu.be/NMvi8jxEYMo

### Expected behaviour

should not put you in the air  

### Steps to reproduce

go on the nuke town map
then start shooting 

### CMG User ID

135

**Comment by stony5** [comment]
after doing more testing it only happens with a mosin

**Comment by crazychris2404** [comment]
This sometimes occurs but not enough to become a major issue currently 
Going to wait and see if there are any more major reports of this

**Comment by crazychris2404** [comment]
After lots of testing with different people there are no major issues within and very rare for problems to occur
